version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: easyged_db
    environment:
      POSTGRES_DB: easyged
      POSTGRES_USER: easyged
      POSTGRES_PASSWORD: easyged
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
