[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "php83Extensions.curl", "bash"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "chmod +x start.sh"]

[start]
cmd = "bash start.sh"
